version: "3.4"

services:
        sonarqube:
                container_name: ct-sonar
                image: sonarqube:8.9-community
                ports:
                        - '9001:9000'
                        - '9092:9092'
                volumes:
                        - ./sonarqube/data:/opt/sonarqube/data
                        - ./sonarqube/logs:/opt/sonarqube/logs
                        - ./sonarqube/extensions:/opt/sonarqube/extensions
                environment:
                        - ALLOW_EMPTY_PASSWORD=no
                        - SONARQUBE_JDBC_USERNAME=sonar
                        - SONARQUBE_JDBC_PASSWORD=testtesttest
        elasticsearch:
                image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
                container_name: ct-elasticsearch
                environment:
                        - bootstrap.memory_lock=true
                        - discovery.type=single-node
                        - ELASTIC_USERNAME=elastic
                        - ELASTIC_PASSWORD=testtesttest
                        - xpack.security.enabled=true
                        - TZ=Africa/Casablanca
                volumes:
                        - esdata:/usr/share/elasticsearch/data
                ulimits:
                        memlock:
                                soft: -1
                                hard: -1
                ports:
                        - 9200:9200
        fluentd:
                container_name: ct-fluentd
                build: ./fluentd
                environment:
                        TZ: Africa/Casablanca
                volumes:
                        - ./fluentd/conf:/fluentd/etc
                ports:
                        - "24224:24224"
                        - "24224:24224/udp"

volumes:
        esdata:
                driver: local
