server:
  port: 9090

spring:
  datasource:
    url: jdbc:h2:mem:cirestechdb
#    url: jdbc:h2:file:./cirestechdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
#    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
#  h2.console:
#    enabled: true
#    path: /h2-ui

#springdoc:
#  swagger-ui.path: /swagger-ui.html

application:
  jwt:
    secretKey: bvTdfFSDcGyDfFFbtrHiPUgeFgfHGCVFqddgjjwdfFhYJtYjwqdvgbyuuiiOiUOfASCasXcFGgHef
    tokenPrefix: 'Bearer '
    tokenExpirationAfterDays: 10
